stages:
  - build-211-dev
  - build-211-sit
  - build-211-uat
  - build-211-pro
  - build-211-test
  - web-dev
  - web-uat1
  - deploy
variables:
  project: webapp
  targetpage: webapp
  hostname: m.yxzq.com
  pathname: webapp

build-211-test:
  stage: build-211-test
  only:
    refs:
      - /^test$/
    variables:
      - $CI_COMMIT_MESSAGE =~ /\-\-build/
  script:
    - sh /root/front-shell/test/webapp-entry.sh -b sit -p /www/test/webapp
  tags:
    - web-dev
build-211-dev:
  stage: build-211-dev
  only:
    refs:
      - /^dev$/
    variables:
      - $CI_COMMIT_MESSAGE =~ /\-\-build/
  script:
    - sh /root/front-shell/test/webapp-entry.sh -b dev
  tags:
    - web-dev
build-211-sit:
  stage: build-211-sit
  only:
    refs:
      - /^sit$/
    variables:
      - $CI_COMMIT_MESSAGE =~ /\-\-build/
  script:
    - sh /root/front-shell/test/webapp-entry.sh -b sit
  tags:
    - web-dev
build-211-uat:
  stage: build-211-uat
  only:
    refs:
      - /^uat$/
    variables:
      - $CI_COMMIT_MESSAGE =~ /\-\-build/
  script:
    - sh /root/front-shell/test/webapp-entry.sh -b uat
  tags:
    - web-dev
build-211-pro:
  stage: build-211-pro
  only:
    refs:
      - /^master$/
    variables:
      - $CI_COMMIT_MESSAGE =~ /\-\-build/
  script:
    - sh /root/front-shell/test/webapp-entry.sh -b pro
  tags:
    - web-dev

web-dev:
  stage: web-dev
  only:
    refs:
      - /^dev$/
    variables:
      - $CI_COMMIT_MESSAGE =~ /\-\-build/
  script:
    - sh /home/gitlab/front-shell/projects/common/entry.sh
  tags:
    - web-dev
web-uat1:
  stage: web-uat1
  only:
    refs:
      - /^jun-ci$/
    variables:
      - $CI_COMMIT_MESSAGE =~ /\-\-build/
  script:
    - sh /home/gitlab/front-shell/projects/common/entry.sh
  tags:
    - web-uat1
deploy:
  stage: deploy
  only:
    - tags
    - master
  script:
    - sh /home/gitlab/front-shell/projects/common/deploy.sh
  tags:
    - web-uat1