stages:
  - dev
  - sit
  - uat1
  - pro
  - deploy
variables:
  project: wealth
  targetpage: webapp
  gitRep: wealth
  proRep: m_yxzq_com-wealth

dev:
  stage: dev
  only:
    refs:
      - /^dev$/
    variables:
      - $CI_COMMIT_MESSAGE =~ /\-\-build/
  script:
    - sh /home/gitlab/front-shell/projects/youxin-webapp/entry.sh -b dev
  tags:
    - web-dev
sit:
  stage: sit
  only:
    refs:
      - /^sit$/
    variables:
      - $CI_COMMIT_MESSAGE =~ /\-\-build/
  script:
    - sh /home/gitlab/front-shell/projects/youxin-webapp/entry.sh -b sit
  tags:
    - web-sit
uat1:
  stage: uat1
  only:
    refs:
      - /^uat$/
    variables:
      - $CI_COMMIT_MESSAGE =~ /\-\-build/
  script:
    - sh /home/gitlab/front-shell/projects/youxin-webapp/entry.sh -b uat
  tags:
    - web-uat1
pro:
  stage: pro
  only:
    refs:
      - /^master$/
    variables:
      - $CI_COMMIT_MESSAGE =~ /\-\-build/
  script:
    - sh /home/gitlab/front-shell/projects/youxin-webapp/entry.sh -b pro
  tags:
    - web-uat1
deploy:
  stage: deploy
  only:
    - tags
  script:
    - sh /home/gitlab/front-shell/projects/common/deploy.sh
  tags:
    - web-uat1